sudo: required
dist: trusty

language: python
python:
  # We don't actually use the Travis Python (since we are on conda), but this keeps it organized.
  - "3.6"

install:
  ##########################################
  ## To pull cached miniconda and update: ##
  ##########################################
  # Get and install anaconda (https://conda.io/docs/travis.html) and packages
  - if [ -d $HOME/miniconda ]; then echo "ls HOME/miniconda:" ; ls $HOME/miniconda ; fi ;
  - if [ ! -d $HOME/miniconda/bin ] ; then
      if [ -d $HOME/miniconda ] ; then rm -rf $HOME/miniconda ; fi ;
      wget -nv https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh ;
      bash miniconda.sh -b -p $HOME/miniconda ;
      export PATH=$HOME/miniconda/bin:$PATH ;
      hash -r ;
      conda config --set always_yes yes --set changeps1 no ;
      conda update -q conda ;
      conda env create -n vcf_stuff --file environment.yml ;
    else
      export PATH=$HOME/miniconda/bin:$PATH ;
      echo "else ls HOME/miniconda:" ; ls $HOME/miniconda ;
      conda config --set always_yes yes --set changeps1 no ;
      conda env update -f environment.yml ;
    fi
  - source activate vcf_stuff
  # Useful for debugging any issues with conda
  - conda info -a
  # Installing the codebase (source code was automatically cloned into CWD by Travis)
  - pip install -e .

#cache:
#  directories:
#    - $HOME/miniconda
#  timeout: 600  # allow 10 minutes to cache instead of default 3 minutes

env:
  - TEST=test.py:TestEvalVcf.test_preset_ref
  - TEST=test.py:TestEvalVcf.test_custom_ref
  - TEST=test.py:TestEvalCnv
  - TEST=test.py:TestPonAnno
  - TEST=test.py:TestPoNPipeline
  - TEST=test.py:TestNormVcf
  - TEST=test.py:TestPcgrPrep

script: 
  - nosetests --nocapture tests/$TEST

