name: vcf_stuff

channels:
  - bioconda
  - conda-forge
  - defaults
  - vladsaveliev
  - anaconda

dependencies:
  - python>=3.6
  - bcftools
  - tabix
  - bedops
  - bedtools
  - vcfanno
  - vcflib  # for VCF normalization
  - snakemake
  - pythonpy
  - click
  - cyvcf2
  - pandas
  #
  # Visualisation
  - jupyter
  - matplotlib
  - matplotlib-venn
  - pip:
    - "--editable=git+https://github.com/vladsaveliev/NGS_Utils#egg=ngs_utils"
    - "--editable=git+https://github.com/umccr/python_utils#egg=python_utils"