name: vcf_stuff

channels:
  - vladsaveliev
  - bioconda
  - conda-forge
  - defaults
  - anaconda

dependencies:
  - python>=3.6
  - bcftools
  - tabix
  - bedops
  - bedtools
  - vcfanno
  - vcflib  # for VCF normalization
  - snakemake-minimal
  - pythonpy
  - click
  - cyvcf2>=0.10.0
  - numpy>=1.15.0
  - pandas
  - ngs_utils
  - nose
  - bed_annotation>=1.0.8
  #
  # Visualisation
  - jupyter
  - matplotlib
  - matplotlib-venn
  #
  # Actively developed accompanying libraries
  - pip:
    - "--editable=git+https://github.com/umccr/hpc_utils#egg=hpc_utils"
    - "--editable=git+https://github.com/vladsaveliev/NGS_Utils#egg=ngs_utils"
