{% set data=load_setup_py_data() %}

package:
  name: vcf_stuff
  version: {{ data.version }}

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - ngs_utils >=2.9.2
  run:
    - python {{ python }}
    - ngs_utils >=2.9.2
    - bcftools
    - tabix
    - bedops
    - bedtools
    - vcfanno
    - vcflib  # for VCF normalization
    - snakemake-minimal
    - pythonpy
    - click
    - cyvcf2 >=0.10.0
    - numpy >=1.15.0
    - pandas
    - ngs_utils
    - nose
    - bed_annotation >=1.1.4
    - reference_data
    - gsort  # https://github.com/brentp/gsort
    - pyensembl

test:
  imports:
    - vcf_stuff.eval_cnv

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
