samples:
    ensemble:    /Users/vsaveliev/Analysis/snv_validation/dream_syn3_grch37/syn3-ensemble-annotated.vcf.gz
    mutect:      /Users/vsaveliev/Analysis/snv_validation/dream_syn3_grch37/syn3-mutect2-annotated.vcf.gz
    vardict:     /Users/vsaveliev/Analysis/snv_validation/dream_syn3_grch37/syn3-vardict-annotated.vcf.gz
    varscan:     /Users/vsaveliev/Analysis/snv_validation/dream_syn3_grch37/syn3-varscan-annotated.vcf.gz
    ensemble-single:  /Users/vsaveliev/Analysis/snv_validation/dream_syn3_grch37/syn3-tumor-single-ensemble-annotated.vcf.gz
    vardict-single:   /Users/vsaveliev/Analysis/snv_validation/dream_syn3_grch37/syn3-tumor-single-vardict-annotated.vcf.gz
    varscan-single:   /Users/vsaveliev/Analysis/snv_validation/dream_syn3_grch37/syn3-tumor-single-varscan-annotated.vcf.gz

# regions: /Users/vsaveliev/Analysis/snv_validation/dream_syn3_grch37/NGv3.bed

truth_variants:  GRCh37/validation/dream-syn3/truth_small_variants.vcf.gz
# truth_regions:   GRCh37/validation/dream-syn3/truth_regions.bed
reference_fasta: GRCh37/seq/GRCh37.fa
