
[[annotation]]
file="/data/cephfs/punim0010/local/development/bcbio/genomes/Hsapiens/GRCh37/variation/gnomad_genome.vcf.gz"
fields = ["AF", "FILTER", "ID"]

names = ["gno_af_all", "gno_filter", "gno_id"]
ops=["self", "self", "self"] 

[[annotation]]
file="/data/cephfs/punim0010/local/development/bcbio/genomes/Hsapiens/GRCh37/variation/clinvar.vcf.gz"
fields=["CLNSIG", "CLNDBN"]
names=["clinvar_pathogenic", "clinvar_disease_name"]
ops=["self", "self"]

[[annotation]]
file="/data/cephfs/punim0010/local/development/bcbio/genomes/Hsapiens/GRCh37/variation/dbsnp-150.vcf.gz"
fields=["ID"]
names=["dbsnp_id"]
ops=["self"]

# convert 5 to 'pathogenic', 255 to 'unknown', etc.
[[postannotation]]
fields=["clinvar_pathogenic"]
op="lua:clinvar_sig(clinvar_pathogenic)"
name="clinvar_sig"
type="String"

[[postannotation]]
fields=["clinvar_sig", "gno_af_all"]
op="lua:check_clinvar_aaf(clinvar_sig, gno_af_all, 0.005)"
name="common_pathogenic"
type="Flag"

[[postannotation]]
name="ID"
fields=["gno_id", "dbsnp_id"]
op="lua:setid(gno_id, dbsnp_id)"
type="String"