import os
from ngs_utils.file_utils import splitext_plus
from hpc_utils import hpc
from vcf_stuff.vcf_normalisation import make_normalise_cmd


ref = hpc.get_ref_file('GRCh37', key='fa')


vcf_file = 'test.vcf.gz'


rule all:
    input:
        expand('norm/res/{sample}.vcf.gz', sample=[splitext_plus(vcf_file)[0]])


rule bgzip:
    input:
        '{sample}.vcf'
    output:
        'norm/work/{sample}.vcf.gz'
    priority: 1
    shell:
        'bgzip -c {input} > {output} && tabix -p vcf {output}'


rule copy:
    input:
        '{sample}.vcf.gz'
    output:
        'norm/work/{sample}.vcf.gz'
    shell:
        'ln -s {input} {output}'


rule normalize_vcf:
    input:
        vcf = 'norm/work/{sample}.vcf.gz',
        ref = ref
    output:
        'norm/res/{sample}.vcf.gz'
    shell:
        make_normalise_cmd('{input.vcf}', '{output[0]}', '{input.ref}')
