#!/usr/bin/env python

import click
from hpc_utils import hpc
from ngs_utils.call_process import run_simple
from ngs_utils.utils import set_locale; set_locale()
from vcf_stuff.vcf_normalisation import make_normalise_cmd

@click.command()
@click.argument('input_file', type=click.Path(exists=True))
@click.option('-o', 'output_file', type=click.Path())
@click.option('-g', 'genome', type=click.Path(), default='GRCh37')
@click.option('-f', '--ref-fasta', 'ref_fasta', type=click.Path())
def main(input_file, output_file, genome=None, ref_fasta=None):
    """
    Normalizes VCF:
    - splits multiallelic ALT
    - splits MNP into single SNPs
    - left-aligns indels
    """
    reference_fasta = hpc.get_ref_file(genome=genome, path=ref_fasta)
    cmd = make_normalise_cmd(input_file, output_file, reference_fasta)
    run_simple(cmd)


if __name__ == '__main__':
    main()

