#!/usr/bin/env python

import click
from ngs_utils.file_utils import adjust_path
from ngs_utils.call_process import run_simple
from ngs_utils.utils import set_locale; set_locale()
from vcf_stuff.vcf_normalisation import make_normalise_cmd

@click.command()
@click.argument('input_file', type=click.Path(exists=True))
@click.option('-o', 'output_file', type=click.Path())
@click.option('-f', '--ref-fasta', 'ref_fasta', type=click.Path(exists=True))
def main(input_file, output_file, ref_fasta=None):
    """
    Normalizes VCF:
    - splits multiallelic ALT
    - splits MNP into single SNPs
    - left-aligns indels
    """
    cmd = make_normalise_cmd(input_file, output_file, adjust_path(ref_fasta))
    run_simple(cmd)


if __name__ == '__main__':
    main()

