[[annotation]]
file="panel_of_normals.snps.vcf.gz"
fields=["PoN_samples"]
ops=["max"]
names=["PoN_CNT"]

[[annotation]]
file="panel_of_normals.indels.vcf.gz"
fields=["PoN_samples"]
ops=["max"]
names=["PoN_CNT"]
