name: CI

on:
  push:
    branches:
      - master

env:
  atoken: ${{ secrets.ANACONDA_UPLOAD_TOKEN }}
  recipe_path: conda/vcf_stuff
  VERSION: '0.6.4' # versioned by bump2version
jobs:
  build-test-publish:
    # When merging to one of the branches above and the commit message matches
    if: "startsWith(github.event.head_commit.message, 'Bump version:')"
    name: Build conda packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Miniconda setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: env1
          mamba-version: "*"
          channels: "umccr,conda-forge,bioconda"
      - name: 🐍 Conda pkg build and upload
        run: |
          conda activate
          mamba create --name cbuildenv conda-build conda-verify anaconda-client boa versionpy
          conda activate cbuildenv
          conda mambabuild --python=${{ matrix.python-version }} ${recipe_path} --token ${atoken}

      - name: 🏁 Test
        run: |
          conda activate
          mamba create --name testenv -c local vcf_stuff
          conda activate testenv
          python -c "import vcf_stuff.eval_cnv"
          nosetests --nocapture tests/test.py:TestPonAnno
          nosetests --nocapture tests/test.py:TestPcgrPrep
